services:
  postgres:
    image: postgres:18.1
    container_name: pg_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./db/pg-data:/var/lib/postgresql

  mariadb:
    image: mariadb:11.8
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./db/mariadb_data:/var/lib/mysql
